const C=window.CONTROL_TOWER_CONFIG||{};let D=null,A=[],view="control";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const e=s=>String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const n=v=>{const x=Number(String(v??"").replace(/,/g,""));return Number.isFinite(x)?x:0};
const fmt=v=>new Intl.NumberFormat("en-IN").format(n(v));const val=v=>v===null||v===undefined||v===""?"—":String(v);
const age=m=>{m=Math.max(0,Math.round(n(m)));return m<60?`${m} min`:`${Math.floor(m/60)}h${m%60?` ${m%60}m`:""}`};
const cls=s=>{s=String(s||"").toLowerCase();return s.includes("stale")?"danger":s.includes("waiting")||s.includes("pending")?"waiting":s.includes("loading")||s.includes("unloading")?"active":""};
function toast(t){$("#toast").textContent=t;$("#toast").classList.remove("hidden");clearTimeout(toast.t);toast.t=setTimeout(()=>$("#toast").classList.add("hidden"),2500)}
function setView(v){view=v;$$(".view").forEach(x=>x.classList.toggle("active",x.id===`view-${v}`));$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.view===v));$("#pageTitle").textContent={control:"Control Tower",docks:"Live Dock Board",search:"Universal Search",alerts:"Alerts & Action Centre",analytics:"Analytics",reports:"Automated Reports"}[v];$("#sidebar").classList.remove("open");scrollTo({top:0,behavior:"smooth"})}
$$(".nav").forEach(b=>b.onclick=()=>setView(b.dataset.view));$$(".jump").forEach(b=>b.onclick=()=>setView(b.dataset.to));$("#menuBtn").onclick=()=>$("#sidebar").classList.toggle("open");
$("#themeToggle").onclick=()=>{const r=document.documentElement,t=r.dataset.theme==="light"?"dark":"light";r.dataset.theme=t;localStorage.theme=t;drawCharts()};document.documentElement.dataset.theme=localStorage.theme||"dark";
function clock(){const d=new Date;$("#liveDate").textContent=d.toLocaleDateString("en-IN",{weekday:"short",day:"2-digit",month:"short"});$("#liveTime").textContent=d.toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit",second:"2-digit"})}clock();setInterval(clock,1000);
async function api(p){const u=new URL(C.API_URL);Object.entries(p).forEach(([k,v])=>u.searchParams.set(k,v));u.searchParams.set("_",Date.now());const r=await fetch(u,{redirect:"follow"});if(!r.ok)throw Error(`Server ${r.status}`);const j=await r.json();if(!j.ok)throw Error(j.error||"Request failed");return j}
async function load(silent=false){if(!silent){$("#systemStatus").textContent="Refreshing";$("#refreshBtn").disabled=true}try{D=await api({action:"dashboard"});A=D.alerts||[];render();$("#systemStatus").textContent="Live";$("#syncText").textContent=`Synced ${new Date(D.generatedAt).toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"})}`}catch(x){$("#systemStatus").textContent="Connection issue";$("#syncText").textContent=x.message;toast(x.message)}finally{$("#refreshBtn").disabled=false}}
$("#refreshBtn").onclick=()=>load();setInterval(()=>load(true),(C.REFRESH_SECONDS||60)*1000);
function render(){renderKpis();renderMiniDocks();renderDocks();renderAlerts();renderAnalytics();renderReport();drawCharts();$("#alertBadge").textContent=A.length}
function renderKpis(){const k=D.kpis||{},x=[["Active Vehicles",k.activeVehicles,`${k.atDock||0} at dock`,"green"],["Occupied Docks",k.occupiedDocks,`${k.multiVehicleDocks||0} multi-vehicle`,""],["Waiting in Yard",k.waitingYard,"Arrival done, Dock In pending","yellow"],["Loading / Unloading",k.inOperation,`${k.loading||0} loading • ${k.unloading||0} unloading`,"purple"],["Dock Out Pending",k.operationCompletePending,"Operation complete, dock blocked","yellow"],["Critical Alerts",k.criticalAlerts,`${k.staleEntries||0} stale entries`,"red"]];$("#kpiGrid").innerHTML=x.map(a=>`<article class="kpi ${a[3]}"><span>${e(a[0])}</span><strong>${fmt(a[1])}</strong><small>${e(a[2])}</small></article>`).join("")}
function renderMiniDocks(){const x=(D.docks||[]).slice(0,15);$("#miniDocks").innerHTML=x.length?x.map(d=>`<article class="mini-dock" data-dock="${e(d.dockNo)}"><div><strong>Dock ${e(d.dockNo)}</strong><i>${d.vehicles.length}</i></div><p>${e(d.vehicles.map(v=>v.vehicle||"Vehicle missing").join(", "))}</p><small>${e(d.vehicles.map(v=>v.status).join(" • "))}</small></article>`).join(""):`<div class="message">No active dock.</div>`;$$(".mini-dock").forEach(c=>c.onclick=()=>{setView("search");$("#searchInput").value=c.dataset.dock;document.querySelector('input[name=type][value=dock]').checked=true;$("#searchForm").requestSubmit()})}
function match(v,f){if(f==="all")return true;if(f==="FWD"||f==="RTO")return String(v.tracker).startsWith(f);return v.movement===f}
function renderDocks(){const f=$("#dockFilter").value,x=(D.docks||[]).map(d=>({...d,vehicles:d.vehicles.filter(v=>match(v,f))})).filter(d=>d.vehicles.length);$("#dockBoard").innerHTML=x.length?x.map(d=>`<article class="dock-card"><div class="dock-head"><h3>Dock ${e(d.dockNo)}</h3><span>${d.vehicles.length} active vehicle${d.vehicles.length===1?"":"s"}</span></div><div class="dock-list">${d.vehicles.map(v=>`<div class="dock-vehicle"><div class="dock-vehicle-top"><div><strong>${e(v.vehicle||"Vehicle missing")}</strong><p>${e(v.tracker)} • ${e(v.route||"Route missing")}</p></div><span class="status ${cls(v.status)}">${e(v.status)}</span></div><div class="dock-meta"><span>Dock In: ${e(val(v.dockIn))}</span><span>Age: ${e(age(v.ageMinutes))}</span><span>Trip: ${e(val(v.tripId))}</span></div></div>`).join("")}</div></article>`).join(""):`<div class="message">No active dock matches this filter.</div>`}
$("#dockFilter").onchange=renderDocks;
function renderAlerts(){const c=A.filter(x=>x.priority==="critical").slice(0,5);$("#criticalCount").textContent=`${c.length} critical`;$("#priorityAlerts").innerHTML=c.length?c.map(a=>`<article class="alert-item ${e(a.priority)}"><i></i><div><strong>${e(a.issue)}</strong><p>${e(a.vehicle||"Unknown")} • ${e(a.tracker||"Unknown")} • Dock ${e(a.dockNo||"—")}</p></div><time>${e(age(a.ageMinutes))}</time></article>`).join(""):`<div class="message">No critical alert right now.</div>`;const q=D.alertCounts||{};$("#alertKpis").innerHTML=[["Total Alerts",A.length],["Critical",q.critical||0],["Warnings",q.warning||0],["Data Quality",q.data||0]].map(x=>`<article class="alert-kpi"><span>${x[0]}</span><strong>${fmt(x[1])}</strong></article>`).join("");renderAlertTable()}
function renderAlertTable(){const f=$("#alertFilter").value,x=A.filter(a=>f==="all"||a.priority===f);$("#alertTable").innerHTML=x.length?x.map(a=>`<tr><td><span class="priority ${e(a.priority)}">${e(a.priority)}</span></td><td>${e(val(a.vehicle))}</td><td>${e(val(a.tracker))}</td><td>${e(val(a.dockNo))}</td><td>${e(val(a.route))}</td><td>${e(a.issue)}</td><td>${e(age(a.ageMinutes))}</td></tr>`).join(""):`<tr><td colspan="7">No alerts in this category.</td></tr>`}
$("#alertFilter").onchange=renderAlertTable;
function metric(label,text,width=100){return `<div class="metric"><strong>${e(label)}</strong><span>${e(text)}</span><div class="bar"><i style="width:${Math.max(5,width)}%"></i></div></div>`}
function renderAnalytics(){const p=D.processMix||[],pm=Math.max(1,...p.map(x=>x.count));$("#processMix").innerHTML=p.map(x=>metric(x.tracker,`${x.count}`,x.count/pm*100)).join("");const s=D.shiftBreakdown||[];$("#shiftMetrics").innerHTML=s.length?s.map(x=>metric(x.shift||"Unknown",`${fmt(x.vehicles)} vehicles • ${fmt(x.shipments)} shipments`)).join(""):`<div class="message">No shift data.</div>`;const r=D.routeBreakdown||[],rm=Math.max(1,...r.map(x=>x.shipments));$("#routeMetrics").innerHTML=r.length?r.map(x=>metric(x.route,`${fmt(x.shipments)} shipments`,x.shipments/rm*100)).join(""):`<div class="message">No route data.</div>`;const q=D.quality||{};$("#qualityMetrics").innerHTML=[["Short",q.short||0],["Excess",q.excess||0],["Missing Route",q.missingRoute||0],["Missing Trip ID",q.missingTripId||0],["Stale Open Entries",q.stale||0]].map(x=>metric(x[0],fmt(x[1]))).join("")}
function renderReport(){$("#reportText").textContent=D.reportText||"Report unavailable"}
$("#copyReport").onclick=async()=>{try{await navigator.clipboard.writeText($("#reportText").textContent);toast("Report copied")}catch{toast("Copy failed")}};
function colors(){const s=getComputedStyle(document.documentElement);return{a:s.getPropertyValue("--primary").trim(),b:s.getPropertyValue("--purple").trim(),m:s.getPropertyValue("--muted").trim(),l:s.getPropertyValue("--line").trim()}}
function chart(canvas,data){if(!canvas||!data?.length)return;const ratio=devicePixelRatio||1,w=canvas.clientWidth||600,h=Number(canvas.height)||250;canvas.width=w*ratio;canvas.height=h*ratio;const c=canvas.getContext("2d");c.scale(ratio,ratio);const z=colors(),p={l:36,r:16,t:16,b:34},cw=w-p.l-p.r,ch=h-p.t-p.b,mv=Math.max(1,...data.map(x=>n(x.vehicles))),ms=Math.max(1,...data.map(x=>n(x.shipments))),xx=i=>p.l+(data.length===1?cw/2:cw/(data.length-1)*i),yv=v=>p.t+ch-n(v)/mv*ch,ys=v=>p.t+ch-n(v)/ms*ch;c.clearRect(0,0,w,h);c.strokeStyle=z.l;c.lineWidth=1;for(let i=0;i<5;i++){const y=p.t+ch/4*i;c.beginPath();c.moveTo(p.l,y);c.lineTo(w-p.r,y);c.stroke()}function line(fn,col){c.strokeStyle=col;c.lineWidth=2.5;c.beginPath();data.forEach((d,i)=>i?c.lineTo(xx(i),fn(d)):c.moveTo(xx(i),fn(d)));c.stroke();c.fillStyle=col;data.forEach((d,i)=>{c.beginPath();c.arc(xx(i),fn(d),3.3,0,Math.PI*2);c.fill()})}line(d=>yv(d.vehicles),z.a);line(d=>ys(d.shipments),z.b);c.fillStyle=z.m;c.font="10px system-ui";c.textAlign="center";data.forEach((d,i)=>c.fillText(d.label,xx(i),h-12))}
function drawCharts(){if(!D)return;requestAnimationFrame(()=>{chart($("#trendChart"),D.dailyTrend||[]);chart($("#analyticsChart"),D.dailyTrend||[])})}addEventListener("resize",()=>{clearTimeout(window.rt);window.rt=setTimeout(drawCharts,180)});
$("#searchForm").onsubmit=async ev=>{ev.preventDefault();const q=$("#searchInput").value.trim(),t=document.querySelector('input[name=type]:checked').value,b=$("#searchBtn");if(!q)return;b.disabled=true;b.textContent="Searching…";$("#searchMessage").classList.add("hidden");$("#activeBlock").classList.add("hidden");$("#historyBlock").classList.add("hidden");try{const x=await api({action:"search",q,type:t});renderSearch(x)}catch(err){$("#searchMessage").textContent=err.message;$("#searchMessage").classList.remove("hidden")}finally{b.disabled=false;b.textContent="Search"}}
function detail(l,v){return `<div class="detail"><span>${e(l)}</span><strong>${e(val(v))}</strong></div>`}
function card(r){return `<article class="vehicle-card"><div class="vehicle-card-head"><div><span class="tracker">${e(r.tracker)}</span><h3>${e(val(r.vehicle))}</h3></div><span class="status ${cls(r.status)}">${e(r.status)}</span></div><div class="details">${detail("Route",r.route)}${detail("Dock",r.dockNo)}${detail("Current Place",r.currentPlace)}${detail("Trip ID",r.tripId)}${detail("Date",r.date)}${detail("Shift",r.shift)}${detail(r.movement==="IB"?"Vehicle Arrived":"Gate In",r.arrivalTime)}${detail("Dock In",r.dockIn)}${detail(r.movement==="IB"?"Unload Time":"Loading Time",r.operationTime)}${detail("Dock Out",r.dockOut)}</div></article>`}
function renderSearch(x){const a=x.active||[],h=x.history||[];$("#searchSummary").innerHTML=`<div><span>Active trips</span><strong>${a.length}</strong></div><div><span>History entries</span><strong>${h.length}</strong></div><div><span>Total matched</span><strong>${x.matched||0}</strong></div>`;$("#searchSummary").classList.remove("hidden");$("#activeTitle").textContent=x.type==="dock"?`Active vehicles at Dock ${x.query}`:"Current vehicle position";$("#activeCount").textContent=a.length;$("#historyCount").textContent=h.length;$("#activeResults").innerHTML=a.map(card).join("");$("#historyResults").innerHTML=h.map(card).join("");$("#activeBlock").classList.toggle("hidden",!a.length);$("#historyBlock").classList.toggle("hidden",!h.length);if(!a.length&&!h.length){$("#searchMessage").textContent="No matching record found.";$("#searchMessage").classList.remove("hidden")}else if(!a.length){$("#searchMessage").textContent="No current active trip. Previous history is shown below.";$("#searchMessage").classList.remove("hidden")}}
if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js").catch(()=>{}));load();
